// Auto-gerado do enum SkillNumber do OpenMU (fonte canonica S6 do servidor).
// PascalCase convertido para nomes legiveis. NAO editar a mao; regenerar se preciso.
using System.Collections.Generic;

namespace Client.Main.Core.Utilities
{
    /// <summary>
    /// Nomes de skill em ingles indexados pelo SkillNumber (S6), usados quando o
    /// skill.bmd local nao fornece nome legivel (cliente KR / formato S20).
    /// </summary>
    public static class SkillNames
    {
        private static readonly Dictionary<int, string> _names = new()
        {
            { 1, "Poison" },
            { 2, "Meteorite" },
            { 3, "Lightning" },
            { 4, "Fire Ball" },
            { 5, "Flame" },
            { 6, "Teleport" },
            { 7, "Ice" },
            { 8, "Twister" },
            { 9, "Evil Spirit" },
            { 10, "Hellfire" },
            { 11, "Power Wave" },
            { 12, "Aqua Beam" },
            { 13, "Cometfall" },
            { 14, "Inferno" },
            { 15, "Teleport Ally" },
            { 16, "Soul Barrier" },
            { 17, "Energy Ball" },
            { 18, "Defense" },
            { 19, "Falling Slash" },
            { 20, "Lunge" },
            { 21, "Uppercut" },
            { 22, "Cyclone" },
            { 23, "Slash" },
            { 24, "Triple Shot" },
            { 26, "Heal" },
            { 27, "Greater Defense" },
            { 28, "Greater Damage" },
            { 30, "Summon Goblin" },
            { 31, "Summon Stone Golem" },
            { 32, "Summon Assassin" },
            { 33, "Summon Elite Yeti" },
            { 34, "Summon Dark Knight" },
            { 35, "Summon Bali" },
            { 36, "Summon Soldier" },
            { 38, "Decay" },
            { 39, "Ice Storm" },
            { 40, "Nova" },
            { 41, "Twisting Slash" },
            { 42, "Rageful Blow" },
            { 43, "Death Stab" },
            { 44, "Crescent Moon Slash" },
            { 45, "Lance" },
            { 46, "Starfall" },
            { 47, "Impale" },
            { 48, "Swell Life" },
            { 49, "Fire Breath" },
            { 50, "Flameof Evil" },
            { 51, "Ice Arrow" },
            { 52, "Penetration" },
            { 55, "Fire Slash" },
            { 56, "Power Slash" },
            { 57, "Spiral Slash" },
            { 58, "Nova Start" },
            { 59, "Combo" },
            { 60, "Force" },
            { 61, "Fire Burst" },
            { 62, "Earthshake" },
            { 63, "Summon" },
            { 64, "Increase Critical Damage" },
            { 65, "Electric Spike" },
            { 66, "Force Wave" },
            { 67, "Stun" },
            { 68, "Cancel Stun" },
            { 69, "Swell Mana" },
            { 70, "Invisibility" },
            { 71, "Cancel Invisibility" },
            { 72, "Abolish Magic" },
            { 73, "Mana Rays" },
            { 74, "Fire Blast" },
            { 76, "Plasma Storm" },
            { 77, "Infinity Arrow" },
            { 78, "Fire Scream" },
            { 79, "Explosion79" },
            { 150, "Monster Skill" },
            { 200, "Summon Monster" },
            { 201, "Magic Attack Immunity" },
            { 202, "Physical Attack Immunity" },
            { 203, "Potionof Bless" },
            { 204, "Potionof Soul" },
            { 210, "Spellof Protection" },
            { 211, "Spellof Restriction" },
            { 212, "Spellof Pursuit" },
            { 213, "Shield Burn" },
            { 214, "Drain Life" },
            { 215, "Chain Lightning" },
            { 217, "Damage Reflection" },
            { 218, "Berserker" },
            { 219, "Sleep" },
            { 221, "Weakness" },
            { 222, "Innovation" },
            { 223, "Explosion223" },
            { 224, "Requiem" },
            { 225, "Pollution" },
            { 230, "Lightning Shock" },
            { 232, "Strikeof Destruction" },
            { 233, "Expansionof Wizardry" },
            { 234, "Recovery" },
            { 235, "Multi Shot" },
            { 236, "Flame Strike" },
            { 237, "Gigantic Storm" },
            { 238, "Chaotic Diseier" },
            { 239, "Doppelganger Self Explosion" },
            { 260, "Killing Blow" },
            { 261, "Beast Uppercut" },
            { 262, "Chain Drive" },
            { 263, "Dark Side" },
            { 264, "Dragon Roar" },
            { 265, "Dragon Slasher" },
            { 266, "Ignore Defense" },
            { 267, "Increase Health" },
            { 268, "Increase Block" },
            { 269, "Charge" },
            { 270, "Phoenix Shot" },
            { 300, "Durability Reduction1" },
            { 301, "Pv P Defence Rate Inc" },
            { 302, "Maximum S Dincrease" },
            { 303, "Automatic Mana Rec Inc" },
            { 304, "Poison Resistance Inc" },
            { 305, "Durability Reduction2" },
            { 306, "Sd Recovery Speed Inc" },
            { 307, "Automatic Hp Rec Inc" },
            { 308, "Lightning Resistance Inc" },
            { 309, "Defense Increase" },
            { 310, "Automatic Ag Rec Inc" },
            { 311, "Ice Resistance Increase" },
            { 312, "Durability Reduction3" },
            { 313, "Defense Success Rate Inc" },
            { 325, "Attack Succ Rate Inc" },
            { 326, "Cyclone Strengthener" },
            { 327, "Slash Strengthener" },
            { 328, "Falling Slash Streng" },
            { 329, "Lunge Strengthener" },
            { 330, "Twisting Slash Streng" },
            { 331, "Rageful Blow Streng" },
            { 332, "Twisting Slash Mastery" },
            { 333, "Rageful Blow Mastery" },
            { 334, "Maximum Life Increase" },
            { 335, "Weapon Mastery Blade Master" },
            { 336, "Death Stab Strengthener" },
            { 337, "Strikeof Destr Str" },
            { 338, "Maximum Mana Increase" },
            { 347, "Pv P Attack Rate" },
            { 348, "Two Handed Sword Strengthener" },
            { 349, "One Handed Sword Strengthener" },
            { 350, "Mace Strengthener" },
            { 351, "Spear Strengthener" },
            { 352, "Two Handed Sword Master" },
            { 353, "One Handed Sword Master" },
            { 354, "Mace Mastery" },
            { 355, "Spear Mastery" },
            { 356, "Swell Life Strengt" },
            { 357, "Mana Reduction" },
            { 358, "Monster Attack Sd Inc" },
            { 359, "Monster Attack Life Inc" },
            { 360, "Swell Life Proficiency" },
            { 361, "Minimum Attack Power Inc" },
            { 362, "Monster Attack Mana Inc" },
            { 378, "Flame Strengthener" },
            { 379, "Lightning Strengthener" },
            { 380, "Expansionof Wiz Streng" },
            { 381, "Inferno Strengthener" },
            { 382, "Blast Strengthener" },
            { 383, "Expansionof Wiz Mas" },
            { 384, "Poison Strengthener" },
            { 385, "Evil Spirit Streng" },
            { 386, "Magic Mastery Grand Master" },
            { 387, "Decay Strengthener" },
            { 388, "Hellfire Strengthener" },
            { 389, "Ice Strengthener" },
            { 397, "One Handed Staff Strengthener" },
            { 398, "Two Handed Staff Strengthener" },
            { 399, "Shield Strengthener Grand Master" },
            { 400, "One Handed Staff Master" },
            { 401, "Two Handed Staff Master" },
            { 402, "Shield Mastery Grand Master" },
            { 403, "Soul Barrier Strength" },
            { 404, "Soul Barrier Proficie" },
            { 405, "Minimum Wizardry Inc" },
            { 413, "Heal Strengthener" },
            { 414, "Triple Shot Strengthener" },
            { 415, "Summoned Monster Str1" },
            { 416, "Penetration Strengthener" },
            { 417, "Defense Increase Str" },
            { 418, "Triple Shot Mastery" },
            { 419, "Summoned Monster Str2" },
            { 420, "Attack Increase Str" },
            { 421, "Weapon Mastery High Elf" },
            { 422, "Attack Increase Mastery" },
            { 423, "Defense Increase Mastery" },
            { 424, "Ice Arrow Strengthener" },
            { 435, "Bow Strengthener" },
            { 436, "Crossbow Strengthener" },
            { 437, "Shield Strengthener High Elf" },
            { 438, "Bow Mastery" },
            { 439, "Crossbow Mastery" },
            { 440, "Shield Mastery High Elf" },
            { 441, "Infinity Arrow Str" },
            { 442, "Minimum Att Power Inc" },
            { 448, "Fire Tome Strengthener" },
            { 449, "Wind Tome Strengthener" },
            { 450, "Lightning Tome Stren" },
            { 451, "Fire Tome Mastery" },
            { 452, "Wind Tome Mastery" },
            { 453, "Lightning Tome Mastery" },
            { 454, "Sleep Strengthener" },
            { 455, "Chain Lightning Str" },
            { 456, "Lightning Shock Str" },
            { 457, "Magic Mastery Summoner" },
            { 458, "Drain Life Strengthener" },
            { 465, "Stick Strengthener" },
            { 466, "Other World Tome Streng" },
            { 467, "Stick Mastery" },
            { 468, "Other World Tome Mastery" },
            { 469, "Berserker Strengthener" },
            { 470, "Berserker Proficiency" },
            { 471, "Minimum Wiz Curse Inc" },
            { 479, "Cyclone Strengthener Duel Master" },
            { 480, "Lightning Strengthener Duel Master" },
            { 481, "Twisting Slash Strengthener Duel Master" },
            { 482, "Power Slash Streng" },
            { 483, "Flame Strengthener Duel Master" },
            { 484, "Blast Strengthener Duel Master" },
            { 485, "Weapon Mastery Duel Master" },
            { 486, "Inferno Strengthener Duel Master" },
            { 487, "Evil Spirit Strengthener Duel Master" },
            { 488, "Magic Mastery Duel Master" },
            { 489, "Ice Strengthener Duel Master" },
            { 490, "Blood Attack Strengthen" },
            { 508, "Fire Burst Streng" },
            { 509, "Force Wave Streng" },
            { 510, "Dark Horse Streng1" },
            { 511, "Critical Dmg Inc Pow Up" },
            { 512, "Earthshake Streng" },
            { 513, "Weapon Mastery Lord Emperor" },
            { 514, "Fire Burst Mastery" },
            { 515, "Crit Dmg Inc Pow Up2" },
            { 516, "Earthshake Mastery" },
            { 517, "Crit Dmg Inc Pow Up3" },
            { 518, "Fire Scream Stren" },
            { 526, "Dark Spirit Str" },
            { 527, "Scepter Strengthener" },
            { 528, "Shield Strengthener Lord Emperor" },
            { 529, "Use Scepter Pet Str" },
            { 530, "Dark Spirit Str2" },
            { 531, "Scepter Mastery" },
            { 532, "Shield Mastery" },
            { 533, "Command Attack Inc" },
            { 534, "Dark Spirit Str3" },
            { 535, "Pet Durability Str" },
            { 551, "Killing Blow Strengthener" },
            { 552, "Beast Uppercut Strengthener" },
            { 554, "Killing Blow Mastery" },
            { 555, "Beast Uppercut Mastery" },
            { 557, "Weapon Mastery Fist Master" },
            { 558, "Chain Drive Strengthener" },
            { 559, "Dark Side Strengthener" },
            { 560, "Dragon Roar Strengthener" },
            { 568, "Equipped Weapon Strengthener" },
            { 569, "Def Success Rate Inc Pow Up" },
            { 571, "Equipped Weapon Mastery" },
            { 572, "Def Success Rate Inc Mastery" },
            { 573, "Stamina Increase Strengthener" },
            { 578, "Durability Reduction1 Fist Master" },
            { 579, "Increase Pv P Defense Rate" },
            { 580, "Increase Maximum Sd" },
            { 581, "Increase Mana Recovery Rate" },
            { 582, "Increase Poison Resistance" },
            { 583, "Durability Reduction2 Fist Master" },
            { 584, "Increase Sd Recovery Rate" },
            { 585, "Increase Hp Recovery Rate" },
            { 586, "Increase Lightning Resistance" },
            { 587, "Increases Defense" },
            { 588, "Increases Ag Recovery Rate" },
            { 589, "Increase Ice Resistance" },
            { 590, "Durability Reduction3 Fist Master" },
            { 591, "Increase Defense Success Rate" },
            { 599, "Increase Attack Success Rate" },
            { 600, "Increase Maximum Hp" },
            { 601, "Increase Maximum Mana" },
            { 603, "Increase Pv P Attack Rate" },
            { 604, "Decrease Mana" },
            { 605, "Recover S Dfrom Monster Kills" },
            { 606, "Recover H Pfrom Monster Kills" },
            { 607, "Increase Minimum Attack Power" },
            { 608, "Recover Mana Monster Kills" },
            { 314, "Cast Invincibility" },
            { 315, "Armor Set Bonus Inc" },
            { 316, "Vengeance" },
            { 317, "Energy Increase" },
            { 318, "Stamina Increase" },
            { 319, "Agility Increase" },
            { 320, "Strength Increase" },
            { 321, "Wingof Storm Abs Pow Up" },
            { 322, "Wingof Storm Def Pow Up" },
            { 323, "Iron Defense" },
            { 324, "Wingof Storm Att Pow Up" },
            { 339, "Death Stab Proficiency" },
            { 340, "Strikeof Destr Prof" },
            { 341, "Maximum Ag Increase" },
            { 342, "Death Stab Mastery" },
            { 343, "Strikeof Destr Mast" },
            { 344, "Blood Storm" },
            { 345, "Combo Strengthener" },
            { 346, "Blood Storm Strengthener" },
            { 363, "Swell Life Mastery" },
            { 364, "Maximum Attack Power Inc" },
            { 366, "Inccritdamagerate" },
            { 367, "Restoresall Mana" },
            { 368, "Restoresall Hp" },
            { 369, "Incexcdamagerate" },
            { 370, "Incdoubledamagerate" },
            { 371, "Incchanceofignore Def" },
            { 372, "Restoresall Sd" },
            { 373, "Inctripledamagerate" },
            { 374, "Eternal Wings Abs Pow Up" },
            { 375, "Eternal Wings Def Pow Up" },
            { 377, "Eternal Wings Att Pow Up" },
            { 390, "Meteor Strengthener" },
            { 391, "Ice Storm Strengthener" },
            { 392, "Nova Strengthener" },
            { 393, "Ice Storm Mastery" },
            { 394, "Meteor Mastery" },
            { 395, "Nova Cast Strengthener" },
            { 406, "Soul Barrier Mastery" },
            { 407, "Maximum Wizardry Inc" },
            { 409, "Illusion Wings Abs Pow Up" },
            { 410, "Illusion Wings Def Pow Up" },
            { 411, "Multi Shot Streng" },
            { 412, "Illusion Wings Att Pow Up" },
            { 425, "Cure" },
            { 426, "Party Healing" },
            { 427, "Poison Arrow" },
            { 428, "Summoned Monster Str3" },
            { 429, "Party Healing Str" },
            { 430, "Bless" },
            { 431, "Multi Shot Mastery" },
            { 432, "Summon Satyros" },
            { 433, "Bless Strengthener" },
            { 434, "Poison Arrow Str" },
            { 443, "Maximum Att Power Inc" },
            { 445, "Dimension Wings Abs Pow Up" },
            { 446, "Dimension Wings Def Pow Up" },
            { 447, "Dimension Wings Att Pow Up" },
            { 459, "Weakness Strengthener" },
            { 460, "Innovation Strengthener" },
            { 461, "Blind" },
            { 462, "Drain Life Mastery" },
            { 463, "Blind Strengthener" },
            { 472, "Berserker Mastery" },
            { 473, "Maximum Wiz Curse Inc" },
            { 475, "Wingof Ruin Abs Pow Up" },
            { 476, "Wingof Ruin Def Pow Up" },
            { 478, "Wingof Ruin Att Pow Up" },
            { 491, "Ice Mastery Duel Master" },
            { 492, "Flame Strike Strengthen" },
            { 493, "Fire Slash Mastery" },
            { 494, "Flame Strike Mastery" },
            { 495, "Earth Prison" },
            { 496, "Gigantic Storm Str" },
            { 497, "Earth Prison Str" },
            { 504, "Emperor Cape Abs Pow Up" },
            { 505, "Emperor Cape Def Pow Up" },
            { 506, "Adds Command Stat" },
            { 507, "Emperor Cape Att Pow Up" },
            { 519, "Electric Spark Streng" },
            { 520, "Fire Scream Mastery" },
            { 521, "Iron Defense Lord Emperor" },
            { 522, "Critical Damage Inc M" },
            { 523, "Chaotic Diseier Str" },
            { 524, "Iron Defense Str" },
            { 536, "Dark Spirit Str4" },
            { 538, "Dark Spirit Str5" },
            { 539, "Spirit Lord" },
            { 592, "Cast Invincibility Fist Master" },
            { 602, "Increase Maximum Ag" },
            { 609, "Increase Maximum Attack Power" },
            { 610, "Increases Crit Damage Chance" },
            { 611, "Recover Mana Fully" },
            { 612, "Recovers Hp Fully" },
            { 613, "Increase Exc Damage Chance" },
            { 614, "Increase Double Damage Chance" },
            { 615, "Increase Ignore Def Chance" },
            { 616, "Recovers Sd Fully" },
            { 617, "Increase Triple Damage Chance" },
        };

        public static bool TryGet(int skillId, out string name) => _names.TryGetValue(skillId, out name);
    }
}
